import { ClipboardCheck, Printer, Stethoscope, Leaf } from 'lucide-react'

function ReceiptScreen({ patientData }) {
  const sections = patientData.summarySections || []
  const now = new Date()
  const isAyush = patientData.consultationType === 'ayush'

  return (
    <div className="flex flex-col items-center flex-1 px-6 py-8 gap-6 max-w-xl mx-auto w-full">
      <div className="w-full bg-white rounded-2xl border shadow-md overflow-hidden print:shadow-none print:border-0">
        <div className={`px-6 py-5 text-center text-white ${isAyush ? 'bg-green-600' : 'bg-blue-600'}`}>
          <div className="flex items-center justify-center gap-2">
            <ClipboardCheck size={22} />
            <h1 className="text-xl font-bold">MediKiosk Clinical Receipt</h1>
          </div>
          <p className="text-white/80 text-xs mt-1">Doctor-ready summary</p>
        </div>

        <div className="px-6 py-4 border-b text-sm text-gray-600 flex justify-between flex-wrap gap-2">
          <span className="flex items-center gap-1.5">
            {isAyush ? <Leaf size={15} className="text-green-600" /> : <Stethoscope size={15} className="text-blue-600" />}
            <strong>{isAyush ? 'AYUSH' : 'Allopathic'}</strong>
          </span>
          <span><strong>Date:</strong> {now.toLocaleDateString()} {now.toLocaleTimeString()}</span>
        </div>

        <div className="px-6 py-4 flex flex-col gap-4">
          {sections.length === 0 && (
            <p className="text-gray-400 text-sm text-center">No summary data available.</p>
          )}
          {sections.map((section) => (
            <div key={section.key}>
              <h3 className="text-xs font-bold uppercase tracking-wide text-blue-600 mb-1">{section.label}</h3>
              <p className="text-gray-800 whitespace-pre-line text-sm">
                {section.content || <span className="text-gray-400">Not reported</span>}
              </p>
            </div>
          ))}
        </div>

        <div className="px-6 py-3 bg-gray-50 border-t text-center text-xs text-gray-400">
          Generated by MediKiosk — for physician review. AI does not diagnose.
        </div>
      </div>

      <button
        onClick={() => window.print()}
        className="flex items-center gap-2 bg-blue-600 text-white px-8 py-3 rounded-xl font-semibold hover:bg-blue-700 transition-all shadow-md print:hidden"
      >
        <Printer size={18} /> Print / Save Receipt
      </button>
    </div>
  )
}

export default ReceiptScreen